In [5]:
from Kit0_script import Matrix

# No Numpy
array=[[1,2,3],[4,5,6],[7,8,9]]
A = Matrix(array)
B = Matrix(array)
print(A)
print(B)
print(A+B)
print(A*B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[[30, 36, 42], [66, 81, 96], [102, 126, 150]]

In [4]:
from Kit0_script import Matrix_np

# Numpy
array=[[1,2,3],[4,5,6],[7,8,9]]
A = Matrix_np(array)
B = Matrix_np(array)
print(A)
print(B)
print(A+B)
print(A*B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

In [3]:
from Kit0_script import Matrix_np_jit

# Numpy with jit
array=[[1,2,3],[4,5,6],[7,8,9]]
A = Matrix_np_jit(array)
B = Matrix_np_jit(array)
print(A)
print(B)
print(A+B)
print(A*B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

In [2]:
from Kit0_script import Matrix_np_njit

# Numpy with njit
array
A=Matrix_np_njit(array)
B=Matrix_np_njit(array)
print(A)
print(B)
print(A+B)
print(A*B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

In [2]:
from Kit0_script import Matrix_njit_p

array=[[1,2,3],[4,5,6],[7,8,9]]
A=Matrix_njit_p(array)
B=Matrix_njit_p(array)
print(A)
print(B)
print(A+B)
print(A*B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

In [2]:
from Functions import Matrix

array=[[1,2,3],[4,5,6],[7,8,9]]
A=Matrix(array)
B=Matrix(array)
print(A)
print(B)
print(A+B)
print(A*B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[[30, 36, 42], [66, 81, 96], [102, 126, 150]]

In [2]:
from Functions import Matrix

array=[[1,2,3],[4,5,6],[7,8,9]]
A=Matrix(array,optimizer='numpy-jit')
B=Matrix(array,optimizer='numpy-jit')
print(A)
print(B)
print(A+B)
print(A*B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

In [3]:
from Functions import Matrix

array=[[1,2,3],[4,5,6],[7,8,9]]
A=Matrix(array,optimizer='numpy-njit')
B=Matrix(array,optimizer='numpy-njit')
print(A)
print(B)
print(A+B)
print(A*B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

In [1]:
from Functions import Matrix

array=[[1,2,3],[4,5,6],[7,8,9]]
A=Matrix(array,optimizer='njit-parallel')
B=Matrix(array,optimizer='njit-parallel')
print(A)
print(B)
print(A+B)
print(A*B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

In [ ]:
from MatCalcul import Matrix,Time_Measurement

time=Time_Measurement()

result_matrix=time.compare_for_severals_matrix_sizes(Matrix,square_size=[1,10,100])
result_matrix

          1         10        100
add  0.000004  0.000009  0.000447
mul  0.000004  0.000058  0.031632

In [2]:
result_matrix_np_jit=time.compare_for_severals_matrix_sizes(Matrix,square_size=[1,10,100,1000],optimizer='numpy-jit')
result_matrix_np_jit

         1         10        100       1000
add  0.000006  0.000002  0.000036  0.010183
mul  0.000003  0.000046  0.000190  0.010095

In [3]:
result_matrix_np_njit=time.compare_for_severals_matrix_sizes(Matrix,square_size=[1,10,100,1000],optimizer='numpy-njit')
result_matrix_np_njit

         1         10        100       1000
add  0.000006  0.000002  0.000015  0.007646
mul  0.000002  0.000005  0.000401  0.011823

In [4]:
result_matrix_njit_p=time.compare_for_severals_matrix_sizes(Matrix,square_size=[1,10,100,1000],optimizer='njit-parallel')
result_matrix_njit_p

         1         10        100       1000
add  0.000010  0.000022  0.000418  0.052670
mul  0.000128  0.000122  0.001193  0.882913